### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by haesleinhuepf** [bercowskya/ZIDAS2022#1]
Hi @bercowskya ,

thanks for sharing this! Just a small request: I wanted to reuse your materials for teaching others, I could only do so if there was a license in the repository clarifying the conditions. If there's no license, nobody is allowed to reuse the material.

Would you mind adding a license file?

https://creativecommons.org/
https://choosealicense.com/

Thanks!

Best,
Robert

**Comment by bercowskya** [comment]
Hi Robert, 
thanks for noticing, it should be solved now ;) 

Enjoy plotting with bokeh! 
Best,
Arianne.

**Comment by haesleinhuepf** [comment]
Thanks for the lightspeed response!
